# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_optional.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/functional_test_data.rb'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

Style/Encoding:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_first_parameter